openapi: 3.0.0

info:
  title: API Service for tracking the COVID-19
  description: 'This repository provides API Service for tracking the Coronavirus(COVID-19) using Novel Coronavirus (COVID-19) Cases[link](https://github.com/CSSEGISandData/COVID-19), provided by [JHU CSSE](https://systems.jhu.edu/).'
  contact:
    email: gadise@gmail.com
  license:
    name: MIT
  version: 0.4.4

servers:
  - url: https://wuhan-coronavirus-api.laeyoung.endpoint.ainize.ai/

tags:
- name: Johns Hopkins CSSE
  description: Data source from Johns Hopkins CSSE

paths:
  /jhu-edu/brief:
    get:
      tags:
      - Johns Hopkins CSSE
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
                properties:
                  result:
                    type: string
        '400':
          description: Bad Request Error
        default:
          description: Unexpected Error
  /jhu-edu/latest:
    get:
      tags:
      - Johns Hopkins CSSE
      parameters:
        - name: iso2
          in: query
          description: Filter by iso2 country code
          schema:
            type: string
            default: US
          required: false
        - name: iso3
          in: query
          description: Filter by iso3 country code
          schema:
            type: string
          required: false
        - name: onlyCountries
          in: query
          description: Make the sum of all the cities or the states in those countries
          schema:
            type: boolean
          required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
                properties:
                  result:
                    type: string
        '400':
          description: Bad Request Error
        default:
          description: Unexpected Error
  /jhu-edu/timeseries:
    get:
      tags:
      - Johns Hopkins CSSE
      parameters:
        - name: iso2
          in: query
          description: Filter by iso2 country code
          schema:
            type: string
            default: US
          required: false
        - name: iso3
          in: query
          description: Filter by iso3 country code
          schema:
            type: string
          required: false
        - name: onlyCountries
          in: query
          description: Make the sum of all the cities or the states in those countries
          schema:
            type: boolean
          required: false    
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
                properties:
                  result:
                    type: string
        '400':
          description: Bad Request Error
        default:
          description: Unexpected Error          
